services:
  - type: web
    name: opentrivia-api
    env: docker
    dockerfilePath: Server/OpenTriviaApp.API/Dockerfile
    dockerContext: Server/OpenTriviaApp.API
    autoDeploy: true
    plan: free

  - type: web
    name: opentrivia-client
    env: docker
    dockerfilePath: Client/opentriviaapp.ui/Dockerfile
    dockerContext: Client/opentriviaapp.ui
    autoDeploy: true
    plan: free